package files;

public class payload {
	
	public static String createTroubleTicket() {
		return "{\r\n"
				+ "    \"ticketType\": \"Incident\",\r\n"
				+ "    \"correlationId\": \"INC000123456\",\r\n"
				+ "    \"status\": \"New\",\r\n"
				+ "    \"severity\": \"3\",\r\n"
				+ "    \"name\": \"Shrikant testing name\",\r\n"
				+ "    \"description\": \"shrikant testing description\",\r\n"
				+ "    \"channel\": {\r\n"
				+ "        \"name\": \"e_bonding\"\r\n"
				+ "    },\r\n"
				+ "    \"note\": [\r\n"
				+ "        {\r\n"
				+ "            \"text\": \"Comment about this Case no comment\",\r\n"
				+ "            \"@type\": \"comments\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"relatedEntity\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"\",\r\n"
				+ "            \"name\": \"S23456789123\",\r\n"
				+ "            \"role\": \"SolutionID\",\r\n"
				+ "            \"@referredType\": \"product\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"\",\r\n"
				+ "            \"name\": \"4567890575F011CA3\",\r\n"
				+ "            \"role\": \"SerialNumber\",\r\n"
				+ "            \"@referredType\": \"asset\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"relatedParty\": [\r\n"
				+ "        {\r\n"
				+ "            \"id\": \"\",\r\n"
				+ "            \"name\": \"MASSMART SERVICE ACC\",\r\n"
				+ "            \"@referredType\": \"customer\"\r\n"
				+ "        }\r\n"
				+ "    ],\r\n"
				+ "    \"attachment\": [\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"PanCard\",\r\n"
				+ "            \"payload\": \"VGhpcyBpcyBhIHRlc3QgZmlsZSBmcm9tIFNob3ByaXRlIHRvIFZvZGFjb20=\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"AadharCard\",\r\n"
				+ "            \"payload\": \"VGhpcyBpcyBhIHRlc3QgZmlsZSBmcm9tIFNob3ByaXRlIHRvIFZvZGFjb20=\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"Passport\",\r\n"
				+ "            \"payload\": \"VGhpcyBpcyBhIHRlc3QgZmlsZSBmcm9tIFNob3ByaXRlIHRvIFZvZGFjb20=\"\r\n"
				+ "        }\r\n"
				+ "    ]\r\n"
				+ "}";
		
	}
	
	public static String updateTroubleTicket() {
		return "{\r\n"
				+ "  \"ticketType\": \"Incident\",\r\n"
				+ "  \"correlationId\": \"INC000123456\",\r\n"
				+ "  \"status\": \"New\",\r\n"
				+ "  \"severity\": \"3\",\r\n"
				+ "  \"name\": \"Shrikant testing name updated\",\r\n"
				+ "  \"description\": \"Shrikant testing description updated\",\r\n"
				+ "  \"channel\": {\r\n"
				+ "    \"name\": \"e_bonding\"\r\n"
				+ "  },\r\n"
				+ "  \"note\": [\r\n"
				+ "    {\r\n"
				+ "      \"text\": \"Updated comment by shrikant on this Case\",\r\n"
				+ "      \"@type\": \"comments\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"relatedEntity\": [\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"\",\r\n"
				+ "      \"name\":\"S23456789123\",\r\n"
				+ "      \"role\": \"SolutionID\",\r\n"
				+ "      \"@referredType\": \"product\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "      \"id\": \"\",\r\n"
				+ "      \"name\": \"4567890575F011CA3\",\r\n"
				+ "      \"role\": \"SerialNumber\",\r\n"
				+ "      \"@referredType\": \"asset\"\r\n"
				+ "    }\r\n"
				+ "  ],\r\n"
				+ "  \"relatedParty\":[ \r\n"
				+ "    {\r\n"
				+ "       \"id\":\"\", \r\n"
				+ "       \"name\":\"MASSMART SERVICE ACC\", \r\n"
				+ "       \"@referredType\":\"customer\" \r\n"
				+ "    } \r\n"
				+ "  ],\r\n"
				+ "    \"attachment\": [\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"SAid\",\r\n"
				+ "            \"payload\": \"VGhpcyBpcyBhIHRlc3QgZmlsZSBmcm9tIFNob3ByaXRlIHRvIFZvZGFjb20=\"\r\n"
				+ "        },\r\n"
				+ "		{\r\n"
				+ "            \"name\": \"Passport\",\r\n"
				+ "            \"payload\": \"VGhpcyBpcyBhIHRlc3QgZmlsZSBmcm9tIFNob3ByaXRlIHRvIFZvZGFjb20=\"\r\n"
				+ "        },\r\n"
				+ "        {\r\n"
				+ "            \"name\": \"Pancard\",\r\n"
				+ "            \"payload\": \"VGhpcyBpcyBhIHRlc3QgZmlsZSBmcm9tIFNob3ByaXRlIHRvIFZvZGFjb20=\"\r\n"
				+ "        }\r\n"
				+ "    ] \r\n"
				+ "}";
		
	}
	
	public static String coursePrice() {
		//dummy or mock response to check complexjsonparse
		return "{\r\n"
				+ "\r\n"
				+ "\"dashboard\": {\r\n"
				+ "\r\n"
				+ "\"purchaseAmount\": 910,\r\n"
				+ "\r\n"
				+ "\"website\": \"rahulshettyacademy.com\"\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "\"courses\": [\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Selenium Python\",\r\n"
				+ "\r\n"
				+ "\"price\": 50,\r\n"
				+ "\r\n"
				+ "\"copies\": 6\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Cypress\",\r\n"
				+ "\r\n"
				+ "\"price\": 40,\r\n"
				+ "\r\n"
				+ "\"copies\": 4\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"RPA\",\r\n"
				+ "\r\n"
				+ "\"price\": 45,\r\n"
				+ "\r\n"
				+ "\"copies\": 10\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "]\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "";
	}
	
	public static String AddBook(String isbn, String aisle) {
		
		String bookPayload = "{\r\n"
		+ "\r\n"
		+ "\"name\":\"Learn Appium Automation with Java\",\r\n"
		+ "\"isbn\":\""+isbn+"\",\r\n"
		+ "\"aisle\":\""+aisle+"\",\r\n"
		+ "\"author\":\"John foe\"\r\n"
		+ "}\r\n"
		+ "";
		return bookPayload;
	}

}
